# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/.Xil/Vivado-32828-TSUKANO/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_Display
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_0
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_1
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_2
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_4
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_3
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_5
  } C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -include {
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_Display
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_0
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_1
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_2
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_4
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_3
    C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/ip/blk_mem_gen_5
  } {
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/.Xil/Vivado-32828-TSUKANO/realtime/blk_mem_gen_Display_stub.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/.Xil/Vivado-32828-TSUKANO/realtime/blk_mem_gen_0_stub.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/.Xil/Vivado-32828-TSUKANO/realtime/blk_mem_gen_1_stub.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/.Xil/Vivado-32828-TSUKANO/realtime/blk_mem_gen_2_stub.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/.Xil/Vivado-32828-TSUKANO/realtime/blk_mem_gen_4_stub.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/.Xil/Vivado-32828-TSUKANO/realtime/blk_mem_gen_3_stub.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/.Xil/Vivado-32828-TSUKANO/realtime/blk_mem_gen_5_stub.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/Coin.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/LFSR.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/charLib_Verilog.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/mixer.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/noiseGenerator.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/pwm.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/sequencer.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/soundEffectCtrl.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/squarewave.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/tenMSecCounter.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/traianglewave_state.v
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/new/famicom.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib xil_defaultlib {
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/imports/PmodOLED_Source/Delay.vhd
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/imports/PmodOLED_Source/OledExample.vhd
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/imports/PmodOLED_Source/OledInit.vhd
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/imports/PmodOLED_Source/PmodOLEDCtrl.vhd
      C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/music_sequencer.srcs/sources_1/imports/PmodOLED_Source/SpiCtrl.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top famicom
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/yuta0/Downloads/music_sequencer/music_sequencer/music_sequencer/.Xil/Vivado-32828-TSUKANO/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
