@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 05 16:38:12 +0900 2023
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Test_famicom_behav -key {Behavioral:sim_1:Functional:Test_famicom} -tclbatch Test_famicom.tcl -protoinst "protoinst_files/design_1.protoinst" -protoinst "protoinst_files/design_3.protoinst" -view C:/Users/yuta0/music_sequencer_2_copy/music_sequencer/music_sequencer.sim/sim_1/Test_sinewave_behav.wcfg -log simulate.log"
call xsim  Test_famicom_behav -key {Behavioral:sim_1:Functional:Test_famicom} -tclbatch Test_famicom.tcl -protoinst "protoinst_files/design_1.protoinst" -protoinst "protoinst_files/design_3.protoinst" -view C:/Users/yuta0/music_sequencer_2_copy/music_sequencer/music_sequencer.sim/sim_1/Test_sinewave_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
